import Footer from "@/src/components/Footer/Footer";
import Header from "@/src/components/Header/Header";
import MenuBar from "@/src/components/Header/MenuBar";
import Links from "@/src/components/Links/Links";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/components/theme-provider";

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "webGhoul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${firaCode.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Links />
          {children}
          <Footer />
          <MenuBar />
        </ThemeProvider>
      </body>
    </html>
  );
}
